animals table pull request
theresetuyi/Vet-clinic-database pull request #1
Opened 2023-07-11 11:13 UTC by theresetuyi

## animal table
-Create tables in SQL.
-Insert and query data in SQL.

2023-07-11 21:23 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @theresetuyi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 21:23 UTC, Qoosim commented on MIT.md
> +SOFTWARE.
- [ ] This is the file that exists in your project and is the one you're supposed to reference in the MIT link not `./LICENSE` file whic does not exist. Kindly reference `./MIT` in the link. 

### 404 error
![license](https://github.com/theresetuyi/Vet-clinic-database/assets/26597432/734c6224-fe43-4bfd-b89b-75cb4e6a3f16)

2023-07-11 21:23 UTC, Qoosim commented on schema.sql
> +    id AUTO_INCREMENT,
- [ ] You did not specify the field type (i.e int) before you add the `AUTO_INCREMENT`. This is the error message I got while trying to create the animals table. You can use something similar to this :point_down: 

```
  id int not null AUTO_INCREMENT

  or 

  id serial
```

![auto-increment](https://github.com/theresetuyi/Vet-clinic-database/assets/26597432/7c69f340-6c24-4b20-a8da-de327721f2f6)

2023-07-11 21:23 UTC, Qoosim commented on schema.sql
> +    date_of_bith DATA,
- [ ] There's a spelling error here. It is supposed to be `date_of_birth` NOT `date_of_bith`. Kindly look into it and fix.
- [ ] It also complains about the type `DATA`. It is supposed to the `date` not `data`. Kindly look into that and fix.


### Error
![spelling-error](https://github.com/theresetuyi/Vet-clinic-database/assets/26597432/e5f82384-64df-464d-95cf-f3048d8cdc8b)

2023-07-11 21:23 UTC, Qoosim commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
- [ ] There's a spelling error in the field `escap_attempts`. The animals table carries `escape_attemps` but you're referencing to `escape_attempts` while populating data into that field. Kindly check and fix it.

### Error
![errro-2](https://github.com/theresetuyi/Vet-clinic-database/assets/26597432/3e1bf137-1e76-4882-93aa-48f7a368bb90)

2023-07-12 10:19 UTC, gemmen29 requested changes
Hi @theresetuyi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Highlights💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 10:19 UTC, gemmen29 commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escap_attempts, neutered, weight_kg)
- [ ] Kindly fix this typo error in the insert statement for the `escap_attempts` as it's called `escape_attempt` in your schema.sql file.

2023-07-12 10:19 UTC, gemmen29 commented on queries.sql
> +SELECT name FROM animals WHERE neutered = true AND escape_attempts < 3;
- [ ] Kindly fix this typo error in the query `List the name of all animals that are neutered and have less than 3 escape attempts` for the `escap_attempts` as it's called `escape_attempt` in your schema.sql file.

2023-07-12 10:19 UTC, gemmen29 commented on queries.sql
> +SELECT name, escape_attempts FROM animals WHERE weight_kg > 10.5;
- [ ] Kindly fix this typo error in the query `List name and escape attempts of animals that weigh more than 10.5kg` for the `escap_attempts` as it's called `escape_attempt` in your schema.sql file.

2023-07-12 10:55 UTC, ShadyShawkat approved these changes
## Hi @theresetuyi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 10:59 UTC, merged